# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b471b4f732309be113ad16be950405f33616ed381c1a84e753a21065eec84ab2ab0cf3985bf3c77c3189dcbd7f22f4d894f2a176f1aad468f6b63e3d2c766122

test:
  secret_key_base: 4ed6703c8e11039db59c60fd869883180c4a78af796a52b4c5c83750647fa8b2b17864683795a1b34da2cb47bb41c63e10aee9af09b6fe3b082d5b7a3234d0b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
