# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35f6bc98c414d144cd55075924ff9f7252b5070557cdddb2dfad9871fd10575e895316f9df13c75a65adbda9cb23eb9dbff8f4084e8419bc306334e5251a30d1

test:
  secret_key_base: b9f635e014d3be9759c4706acce7e3afb5f6e160ae4e63a03b33cba17043ca84c81d219ae8e45b53bee37103af2ba5840edb0c7fbe3fd1f4677f271cef42c047

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
